class NotFoundException(Exception):
  pass

class ValueErrorException(Exception):
  pass
